### ISSUE TITLE
Provider PIP?

### ISSUE THREAD

**Issue by mmatthiesencsc** [eclipse-edc/Publications#17]
What does Provider PIP mean here:
https://github.com/eclipse-dataspaceconnector/Publications/blob/main/Identity%20Management/DID_EDC.md#the-edc-solution
It seems the "only" job is to assert trust in the domain. I would make it clearer that foo.com is a domain controlled by the Participant.
(I suggest to stick to Gaia-X Notation and use Provider/Consumer. The sentence 'both “Participant” and “Provider” are participants in a dataspace' is quite confusing.)

**Comment by PeterKoen-MSFT** [comment]
@jimmarino - can you have a quick check if the document still references the current state of EDC, and if not we need to make some updates to the text?
I'm happy with updates to terminology, however, the Gaia-X Notation of Provider/Consumer is strictly to be avoided as in a dataspace all participants are provider and consumer at the same time and the distinction will make any explanation very messy to read.

**Comment by jimmarino** [comment]
After a quick look, it appears to be accurate, except for the DID example referencing Ethereum. The `foo.com` domain is under the participant's control and should be clearer. I would be careful about modifying other terminology as the EDC has its own vocabulary, which is reflected in this document and we should adhere to that.

**Comment by PeterKoen-MSFT** [comment]
ok, closing this issue. However, minor terminology issues were identified (Components instead of Connector in EDC)
